### DISCUSSION TITLE
GET request to Api for performance numbers as RESTful sensor in Home Assistant?

### DISCUSSION THREAD

**Discussion by Joshndroid** [ghostfolio/ghostfolio#1384] [Q&A] [answered]
Hey All,
I am wondering how to get some values from the api
I can't say I have any real experience in this so forgive me but I have been trying to work it out.

I am trying to get my current portfolio value (and maybe other items if i can get that working) listed as a sensor within a local home assistant instance.

I am self hosting my instance so not too concerned about hitting it every hour or whatever. (I have anonymized the below URL/data values so they are not leaking my info)

It appears they have a restful sensor that can be created as per here;
https://www.home-assistant.io/integrations/sensor.rest/

When poking around in the network dev mode I believe i am trying to access;
https://ghostfolio.com/api/v2/portfolio/performance?range=max

With some mucking about I have managed to run a curl get request in terminal such as this;
`curl -X GET https://ghostfolio.com/api/v2/portfolio/performance?range=max -H "Authorization: Bearer some-big-auth-token"`

and I end up with a huge output of data.

It appears to be everyday... however i can see in there that there is this output.
`
"performance":{"currentValue":$$$$$,"currentGrossPerformance":$$$$$$,"currentGrossPerformancePercent":$$$$$$$,"currentNetPerformance":$$$$$$,"currentNetPerformancePercent":$$$$$$$,"totalInvestment":$$$$$$}}
`
It would seem "currentValue" is what I am after but have no idea how to parse that in order to get the sensor to output that value... 

Thanks for any help.
I did try and have a look through the docs but as I have no real idea other than trial and error so far I am at a bit of a loss.

**Comment by XeroX1988** [comment, marked as answer]
You should be able to parse and extract the JSON on the Home Assistant side, I've done something like this in the past. Pasting a snippet here that might help you out.

I have not tested this, but this should get you two new entities in Home Assistant. 

```
sensor:
  - platform: command_line  
    command: "curl -X GET https://ghostfolio.com/api/v2/portfolio/performance?range=max -H "Authorization: Bearer some-big-auth-token"
    name: Ghostfolio
    json_attributes:
      - performance
    value_template: 'OK'

  - platform: template
    sensors:
      ghostfolio_current_value:
        friendly_name: Ghostfolio Current Value
        unit_of_measurement: "EUR"
        value_template: "{{ states.sensor.ghostfolio.attributes.performance.currentValue }}"
```

You might need an automation to trigger an update though:

```
automation:
  - alias: "update ghostfolio"
    trigger:
      - platform: time
        at: "00:00:50"
    action:
      - service: homeassistant.update_entity
        entity_id: sensor.ghostfolio
```

**Comment by Joshndroid** [comment]
Thank you @XeroX1988 

While what you suggested didn't explicitly work from a cut and paste point (with value change) of view it really did help me with the underlying bits I needed.

I will post here what I got working;

Within my sensors.yaml

```
#GhostFolio Performance Sensor
  - platform: command_line  
    command: 'curl -X GET https://ghostfolio.com/api/v2/portfolio/performance?range=max -H "Authorization: Bearer some-big-auth-token"'
    name: Ghostfolio
    json_attributes:
      - performance
    value_template: 'OK'
```

Within my templates.yaml file

```
#Ghostfolio Current Value
  -  sensor:
        name: Ghostfolio Current Value
        unit_of_measurement: "EUR"
        state: >
            {{ states.sensor.ghostfolio.attributes.performance.currentValue }}
```

Thanks again!!
