### DISCUSSION TITLE
How to install Ghostfolio on a Synology docker system?

### DISCUSSION THREAD

**Discussion by domoticaDude** [ghostfolio/ghostfolio#1413] [Q&A]
How do i install this on a synology Docker? I cant find the instructions.

When i start i get..
![image](https://user-images.githubusercontent.com/79633328/199029438-6960b4ef-418e-4b5c-a9b9-828f4ebb0770.png)

**Comment by dtslvr** [comment]
Hi @domoticaDude

The environment variable `DATABASE_URL` is missing. You need a `.env` file to start the docker container. Please find a sample file [here](https://github.com/ghostfolio/ghostfolio/blob/main/.env).

**Comment by allesauseinerhand** [comment]
Hi @domoticaDude 

I also use Synology and the following docker compose file is working for me:

```
version: '3.8'
services:
  ghostfolio:
    container_name: ghostfolio
    image: ghostfolio/ghostfolio:latest
    ports:
      - 3333:3333
    restart: unless-stopped
    environment:
      DATABASE_URL: 'postgresql://MY_DB_USER:MY_DB_PWD@db:5432/MY_DB_NAME?sslmode=disable'
      NODE_ENV: production
      REDIS_HOST: 'redis'
      REDIS_PORT: 6379
      REDIS_PASSWORD: MY_REDIS_PWD
      ACCESS_TOKEN_SALT: SOME_SUPER_SECRET_SALT
      JWT_SECRET_KEY: SOME_SUPER_SECRET_KEY
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      
  db:
    container_name: ghostfolio-db
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - /volume1/apps_and_dbs/ghostfolio/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: MY_DB_NAME
      POSTGRES_USER: MY_DB_USER
      POSTGRES_PASSWORD: MY_DB_PWD
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "diun.enable=false"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  ghostfolio-db-backup:
    container_name: ghostfolio-db-backup
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - /volume1/apps_and_dbs/ghostfolio/db_backup:/dump
      - /etc/localtime:/etc/localtime:ro
    environment:
      PGHOST: db
      PGUSER: MY_DB_USER
      PGPASSWORD: MY_DB_PWD
      BACKUP_NUM_KEEP: 3
      BACKUP_FREQUENCY: 8h
    depends_on:
      - db
    # Bei folgendem Entrypoint und healthcheck muss db ersetzt werden durch Namen des Datenbank-Containers, 5432 ist Default-Port von Postgres, danach kommt Name der Postgres-Datenbank
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      sleep 2m
      while /bin/true; do
        pg_dump -Fc -h db -p 5432 MY_DB_NAME > /dump/dump_\`date +%d-%m-%Y"_"%H_%M_%S\`.psql
        (ls -t /dump/dump*.psql|head -n $$BACKUP_NUM_KEEP;ls /dump/dump*.psql)|sort|uniq -u|xargs rm -- {}
        sleep $$BACKUP_FREQUENCY
      done
      EOF'
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "diun.enable=false"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h db -p 5432 -d MY_DB_NAME"]
      interval: 20s
      timeout: 5s
      retries: 5

  redis:
    container_name: ghostfolio-redis
    image: 'redis:alpine'
    restart: unless-stopped
    environment:
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      REDIS_PASSWORD: MY_REDIS_PWD
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "diun.enable=false"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      
  # Folgender Service ist normalerweise kommentiert, aber wenn etwas anzupassen ist, dann auskommentieren
  # Anmelden mit den Angaben aus PGADMIN_DEFAULT_EMAIL und PGADMIN_DEFAULT_PASSWORD
  # Mit Datenbank verbinden durch Quick Links > Add new Server > erster Tab > Name z.B. Ghostfolio > zweiter Tab als Server Host db, für User & Co. Angaben aus db-Container verwenden
  # Nach Nichtgebrauch wieder kommentieren, Stack updaten und manuell den pgAdmin-Container removen
  pgadmin:
    container_name: ghostfolio-pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: SOME_RANDOM_MAIL_ADDRESS
      PGADMIN_DEFAULT_PASSWORD: MY_PGADMIN_PASSWORD
    ports:
      - "5050:80"
      
networks:
  default:
    name: ghostfolio_network
    ipam: 
      config:
        - subnet: 172.40.11.0/24
```
