### DISCUSSION TITLE
"P1000: Authentication failed against database server at `postgres`" error

### DISCUSSION THREAD

**Discussion by pippo73** [ghostfolio/ghostfolio#3957] [Q&A]
Try to run docker image, get the error 
_Error: P1000: Authentication failed against database server at `postgres`, the provided database credentials for `user` are not valid._

I just changed the .env file according readme file.

**To Reproduce**

1. deploy docker compose file
2. adapt the env file
3. start the docer

**Expected behavior**

ghostfolio selfhosted server shuld run as expected 

**Logs**

```
$ docker logs ghostfolio-ghostfolio-1 -f
Running database migrations
+ echo Running database migrations
+ npx prisma migrate deploy
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "ghostfolio-db", schema "public" at "postgres:5432"

Error: P1000: Authentication failed against database server at `postgres`, the provided database credentials for `user` are not valid.

Please make sure to provide valid database credentials for the database server at `postgres`.
npm notice
npm notice New minor version of npm available! 10.8.2 -> 10.9.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.9.0
npm notice To update run: npm install -g npm@10.9.0
npm notice


```
**Environment**

- Ghostfolio Version **docker.io/ghostfolio/ghostfolio:latest**
- Self-hosted
- Experimental Features disabled
- Browser none
- OS docker on linux

**Additional context**
```

services:
  ghostfolio:
    image: docker.io/ghostfolio/ghostfolio:latest
    init: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    env_file:
      - ./.env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?connect_timeout=300&sslmode=prefer
      REDIS_HOST: redis
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - 3333:3333
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:3333/api/v1/health']
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: docker.io/library/postgres:15
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_READ_SEARCH
      - FOWNER
      - SETGID
      - SETUID
    security_opt:
      - no-new-privileges:true
    env_file:
      - ./.env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: docker.io/library/redis:alpine
    user: '999:1000'
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    env_file:
      - ./.env
    command: ['redis-server', '--requirepass', $REDIS_PASSWORD]
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli --pass $REDIS_PASSWORD ping | grep PONG']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres:
```
env
```

COMPOSE_PROJECT_NAME=ghostfolio

# CACHE
REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_PASSWORD=RNYznLuA9Zn

# POSTGRES
POSTGRES_DB=ghostfolio-db
POSTGRES_USER=user
POSTGRES_PASSWORD=duA9CShvonDE

# VARIOUS
ACCESS_TOKEN_SALT=b!ZNq4<u4+uP52
DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5432/${POSTGRES_DB}?connect_timeout=300&sslmode=prefer
JWT_SECRET_KEY==24iLzXeiCnXQD

```

this are my commands to be sure that I have no traces of previous ghost
```

$ docker system prune
WARNING! This will remove:
  - all stopped containers
  - all networks not used by at least one container
  - all dangling images
  - unused build cache

Are you sure you want to continue? [y/N] y
Total reclaimed space: 0B


docker ps -a
CONTAINER ID   IMAGE                                           COMMAND                  CREATED             STATUS         PORTS                                       NAMES
a96548a57656   revenz/fenrus                                   "/app/docker-entrypo…"   49 minutes ago      Up 6 minutes   0.0.0.0:3000->3000/tcp, :::3000->3000/tcp   fenrus
8a0949c1a33a   lscr.io/linuxserver/changedetection.io:latest   "/init"                  About an hour ago   Up 6 minutes   0.0.0.0:5000->5000/tcp, :::5000->5000/tcp   changedetection
5a0f47327126   portainer/agent                                 "./agent"                3 hours ago         Up 6 minutes   0.0.0.0:9001->9001/tcp, :::9001->9001/tcp   portainer_agent

$ docker rmi ghostfolio/ghostfolio:latest postgres:15 redis:alpine
Error response from daemon: No such image: ghostfolio/ghostfolio:latest
Error response from daemon: No such image: postgres:15
Error response from daemon: No such image: redis:alpine
```
I have also also tried to do the following command

`docker compose up -d ghostfolio --force-recreate`

but nothing else changes. same error.
I have found a similar [bug ](https://github.com/ghostfolio/ghostfolio/issues/3889) but @dtslvr suggested me to open a new bug..

Hope you can help me pls.

**Comment by sinnerinc** [comment]
For me it worked to add the following to postgres:
```
environment:
       POSTGRES_USER: ${POSTGRES_USER}
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
```

More info on those variables:
https://hub.docker.com/_/postgres


and also the following to ghostfolio:
```
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?connect_timeout=300&sslmode=prefer
      REDIS_HOST: redis
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      ACCESS_TOKEN_SALT: ${ACCESS_TOKEN_SALT}
```

So my docker-compose.yml file looked like that:

```
services:
  ghostfolio:
    image: docker.io/ghostfolio/ghostfolio:latest
    init: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?connect_timeout=300&sslmode=prefer
      REDIS_HOST: redis
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      ACCESS_TOKEN_SALT: ${ACCESS_TOKEN_SALT}
    ports:
      - 3333:3333
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:3333/api/v1/health']
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: docker.io/library/postgres:15
    # ports:
      # - 5555:5432
    environment:
       POSTGRES_USER: ${POSTGRES_USER}
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
       #POSTGRES_HOST_AUTH_METHOD: trust
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_READ_SEARCH
      - FOWNER
      - SETGID
      - SETUID
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - /volume2/docker/ghostfolio/postgres:/var/lib/postgresql/data

  redis:
    image: docker.io/library/redis:alpine
    user: '999:1000'
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    command: ['redis-server', '--requirepass', $REDIS_PASSWORD]
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli --pass "$REDIS_PASSWORD" ping | grep PONG']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres:
```

This worked okay when using docker on WSL2, however when deployed through portainer on my Synology, I removed the healthchecking section as it was giving me some issues, so skipped for now. It works okay since.
