### DISCUSSION TITLE
Ghostfolio Container behing Caddy Reverse Proxy

### DISCUSSION THREAD

**Discussion by DerDominik** [ghostfolio/ghostfolio#4238] [Q&A]
Hi all,

I'd like to use Ghostfolio behind a Caddy Reverse Proxy which is running with other containers without problems.
So I setup a Ghostfolio container as I think it should work (or like all my other container).
From the log it is starting, access to postgresql is given, but I can't open from my subdomain (only a blank page).

My setup looks like this:

Caddy Compose:
```
services:
  caddy:
    container_name: "caddy"
    image: caddy:2
    networks:
      - caddy
    ports:
      - 443:443/tcp
      - 80:80/tcp
    restart: unless-stopped
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/caddy-config:/config
      - CHANGE_TO_COMPOSE_DATA_PATH/caddy-data:/data
      - CHANGE_TO_COMPOSE_DATA_PATH/caddy-files/Caddyfile_ionos:/etc/caddy/Caddyfile:ro
      - CHANGE_TO_COMPOSE_DATA_PATH/caddy-files/caddy_ionos:/usr/bin/caddy

networks:
  caddy:
    external: true
    name: caddy
```

Caddyfile:
```
@sub9 host ghostfolio.dom82.org
  handle @sub9 {
 	reverse_proxy 192.168.99.6:3333
  }
```

Redis Compose:
```
services:
  redis:
    container_name: redis
    environment:
      - GID=100
      - UID=1000
    image: redis:alpine
    networks:
      - "caddy"
    restart: unless-stopped
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/redis:/data

networks:
  caddy:
    external: true
    name: "caddy"
```

PostgreSQL Compose:
```
services:
  postgres:
    container_name: postgres
    environment:
      - GID=100
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=xxxpasswordxxx
      - POSTGRES_USER=xxxuserxxx
      - UID=1000
    image: postgres:12
    networks:
      - "caddy"
    restart: unless-stopped
    volumes:
      - CHANGE_TO_COMPOSE_DATA_PATH/postgres:/var/lib/postgresql/data

networks:
  caddy:
    external: true
    name: "caddy"
```

Ghostfolio Compose:
```
services:
  ghostfolio:
    container_name: ghostfolio
    environment:
      - ACCESS_TOKEN_SALT=xxxtokenxxx
      - BASE_CURRENCY=EUR
      - DATABASE_URL=postgresql://xxxuserxxx:xxxpasswordxxx@postgres:5432/ghostfolio
      - JWT_SECRET_KEY=xxxsecretkeyxxx
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    image: ghostfolio/ghostfolio
    networks:
      - "caddy"
    restart: unless-stopped

networks:
  caddy:
    external: true
    name: "caddy"
```

Everything is starting up, also ghostfolio.
I see that tables inside of PostgreSQL are created, so connection inside should be fine.
And the ghostfolio logs ends with
```
[Nest] 132  - 01/22/2025, 5:29:51 PM     LOG    ________               __  ____      ___
[Nest] 132  - 01/22/2025, 5:29:51 PM     LOG   / ____/ /_  ____  _____/ /_/ __/___  / (_)___
[Nest] 132  - 01/22/2025, 5:29:51 PM     LOG  / / __/ __ \/ __ \/ ___/ __/ /_/ __ \/ / / __ \
[Nest] 132  - 01/22/2025, 5:29:51 PM     LOG / /_/ / / / / /_/ (__  ) /_/ __/ /_/ / / / /_/ /
[Nest] 132  - 01/22/2025, 5:29:51 PM     LOG \____/_/ /_/\____/____/\__/_/  \____/_/_/\____/ 2.132.0
[Nest] 132  - 01/22/2025, 5:29:51 PM     LOG 
[Nest] 132  - 01/22/2025, 5:29:51 PM     LOG Listening at http://0.0.0.0:3333
[Nest] 132  - 01/22/2025, 5:29:51 PM     LOG 
```

But, as written, only a blank page.
Does anyone has an idea how to solve this?

Thanks and best regards,
Dominik

**Comment by pazaan** [comment]
I haven't used Caddy before (I use Traefik on my VPS), but I tried it out on my local machine.
I have it working with the following compose file for Caddy:

docker-compose.caddy.yml:
```
services:
  caddy:
    image: docker.io/caddy:2-alpine
    container_name: gf-caddy
    restart: unless-stopped
    networks:
      - caddy
    ports:
      - 9001:80
      - 9443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile

networks:
  caddy:
     name: caddy
```

My ./Caddyfile looks like this:
```
test.localhost:80, :80 {
	reverse_proxy ghostfolio:3333
}
```

And I added `test.localhost` to my `/etc/hosts` file so that I can access http://test.localhost:9001/

I'm using the standard docker-compose.yml file from the Ghostfolio repo with the following changes:

docker-compose.yml:
```
name: ghostfolio
services:
  ghostfolio:
    ...
    networks:
      - caddy
      - default

  ... other services...

networks:
  caddy:
    external: true
```

I would recommend leaving postgresql and redis on the default network, and not put it on the Caddy network. Ghostfolio should be on both the default network (so that it can talk to redis and postgresql) and the `caddy` network (so that it can talk to Caddy).
