### DISCUSSION TITLE
How to add more platforms?

### DISCUSSION THREAD

**Discussion by Cave-Johnson** [ghostfolio/ghostfolio#735] [Q&A] [answered]
Just spun myself up a local version of this and it looks great. Going through the accounts section, how do I add more platforms to the list?

Looking through closed tickets I can see people have requested some in the past but I can't see these myself in the list?

**Comment by dtslvr** [comment]
Hi @Cave-Johnson

There is no GUI available to add custom platforms at this point. You can add them directly to the database table (`Platform`).

**Comment by Cave-Johnson** [comment]
Would it be worth providing a more complete list of platforms as standard? If so i can provide a list of UK based ones and their logos

**Comment by dtslvr** [comment]
> Would it be worth providing a more complete list of platforms as standard? If so i can provide a list of UK based ones and their logos

It's very kind of you.
As a user I prefer to add a handful of platforms manually rather than deleting dozens of international platforms I don't use. Therefore I'd like to keep it as it is for now. A GUI similar to the currency management would be great, though.

By the way the logo is derived from the `url` of the platform.

**Comment by Cave-Johnson** [comment]
Ah okay, comes from the favicon that makes sense. Are you planning on adding a way to add them through the GUI?

In the short term, how would I interact with the database to add them?

**Comment by dtslvr** [comment]
> In the short term, how would I interact with the database to add them?

You could add a database management software to your [docker-compose.yml](https://github.com/ghostfolio/ghostfolio/blob/main/docker/docker-compose.yml) file such as [adminer](https://hub.docker.com/_/adminer).

<br />

Another possibility is to run these commands via terminal:

```
docker-compose exec postgres psql -U user ghostfolio-db
INSERT INTO "Platform" (id, name, url) VALUES ('1e90c766-8d42-4aed-9440-acb74f6314da', 'IG', 'https://www.ig.com');
```

`id` should be a [random UUID](https://www.uuidgenerator.net). With `CTRL` + `d` you can leave the prompt.

<br />

> Are you planning on adding a way to add them through the GUI?

That would be a nice addition. This feature has low priority for me, though. If you or someone else is interested in implementing it, I'm happy to offer support.

**Comment by jokorn** [comment]
An alternative when interacting with the database is to use prisma studio:
`npx prisma studio`
This worked great for me when I cleaned up and added to my list of platforms...

**Comment by allesauseinerhand** [comment]
Another working alternative to prisma studio or adminer is pgAdmin, which I included in my docker-compose-file at the end:

```
version: '3.8'
services:
  ghostfolio:
    container_name: ghostfolio
    image: ghostfolio/ghostfolio:latest
    ports:
      - 3333:3333
    restart: unless-stopped
    environment:
      DATABASE_URL: 'postgresql://MY_DB_USER:MY_DB_PWD@db:5432/MY_DB_NAME?sslmode=disable'
      NODE_ENV: production
      REDIS_HOST: 'redis'
      REDIS_PORT: 6379
      REDIS_PASSWORD: MY_REDIS_PWD
      ACCESS_TOKEN_SALT: SOME_SUPER_SECRET_SALT
      JWT_SECRET_KEY: SOME_SUPER_SECRET_KEY
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      
  db:
    container_name: ghostfolio-db
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - /volume1/apps_and_dbs/ghostfolio/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: MY_DB_NAME
      POSTGRES_USER: MY_DB_USER
      POSTGRES_PASSWORD: MY_DB_PWD
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "diun.enable=false"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  ghostfolio-db-backup:
    container_name: ghostfolio-db-backup
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - /volume1/apps_and_dbs/ghostfolio/db_backup:/dump
      - /etc/localtime:/etc/localtime:ro
    environment:
      PGHOST: db
      PGUSER: MY_DB_USER
      PGPASSWORD: MY_DB_PWD
      BACKUP_NUM_KEEP: 3
      BACKUP_FREQUENCY: 8h
    depends_on:
      - db
    # Bei folgendem Entrypoint und healthcheck muss db ersetzt werden durch Namen des Datenbank-Containers, 5432 ist Default-Port von Postgres, danach kommt Name der Postgres-Datenbank
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      sleep 2m
      while /bin/true; do
        pg_dump -Fc -h db -p 5432 MY_DB_NAME > /dump/dump_\`date +%d-%m-%Y"_"%H_%M_%S\`.psql
        (ls -t /dump/dump*.psql|head -n $$BACKUP_NUM_KEEP;ls /dump/dump*.psql)|sort|uniq -u|xargs rm -- {}
        sleep $$BACKUP_FREQUENCY
      done
      EOF'
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "diun.enable=false"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h db -p 5432 -d MY_DB_NAME"]
      interval: 20s
      timeout: 5s
      retries: 5

  redis:
    container_name: ghostfolio-redis
    image: 'redis:alpine'
    restart: unless-stopped
    environment:
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      REDIS_PASSWORD: MY_REDIS_PWD
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "diun.enable=false"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      
  # Folgender Service ist normalerweise kommentiert, aber wenn etwas anzupassen ist, dann auskommentieren
  # Anmelden mit den Angaben aus PGADMIN_DEFAULT_EMAIL und PGADMIN_DEFAULT_PASSWORD
  # Mit Datenbank verbinden durch Quick Links > Add new Server > erster Tab > Name z.B. Ghostfolio > zweiter Tab als Server Host db, für User & Co. Angaben aus db-Container verwenden
  # Nach Nichtgebrauch wieder kommentieren, Stack updaten und manuell den pgAdmin-Container removen
  pgadmin:
    container_name: ghostfolio-pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: SOME_RANDOM_MAIL_ADDRESS
      PGADMIN_DEFAULT_PASSWORD: MY_PGADMIN_PASSWORD
    ports:
      - "5050:80"
      
networks:
  default:
    name: ghostfolio_network
    ipam: 
      config:
        - subnet: 172.40.11.0/24
```
