### DISCUSSION TITLE
Deploy Ghostfolio completely with docker-compose

### DISCUSSION THREAD

**Discussion by hari-bo** [ghostfolio/ghostfolio#979] [Q&A]
I want to deploy Ghostfolio with an docker-compose file without external environments file.

Currently i've created this file and every dock has it's own IP adress, but when deploying the first error is that the Ghostfolio container can't reach the Redis container. But when manually testing the IP+port and hostname it's working fine.

```
version: '3.3'

networks:
    Docker-client: 
        external: true

services:
    Ghostfolio:
        container_name: Ghostfolio
        environment:
            - PUID=1032
            - PGID=100
            - TZ=Europe/Amsterdam
            - DATABASE_URL=postgresql://ghostfolio:ghostfolio@192.168.203.220:5432/ghostfolio?sslmode=prefer
            - REDIS_HOST= 'Ghostfolio-Redis'
            - ACCESS_TOKEN_SALT=ghostfolio
            - JWT_SECRET_KEY=ghostfolio
        networks: 
          Docker-client: 
            ipv4_address: 192.168.203.222
        ports:
            - '14082:3333/tcp'
        restart: unless-stopped
        image: ghostfolio/ghostfolio:latest

    Ghostfolio-Postgres:
        container_name: Ghostfolio-Postgres
        environment:
            - PUID=1032
            - PGID=100
            - TZ=Europe/Amsterdam
            - POSTGRES_PASSWORD=ghostfolio
            - POSTGRES_USER=ghostfolio
            - POSTGRES_DB=ghostfolio
        networks: 
          Docker-client: 
            ipv4_address: 192.168.203.220
        ports:
            - '14080:8080/tcp'
        volumes:
            - '/volume2/DOCKER-DATA/Ghostfolio/postgres/data:/var/lib/postgresql/data'
        restart: unless-stopped
        image: postgres:latest

    Ghostfolio-Redis:
        container_name: Ghostfolio-Redis
        environment:
            - PUID=1032
            - PGID=100
            - TZ=Europe/Amsterdam
            - REDIS_HOST=localhost
            - REDIS_PORT=6379
            - ALLOW_EMPTY_PASSWORD=yes
        networks: 
          Docker-client: 
            ipv4_address: 192.168.203.221
        ports:
            - '6379:6379/tcp'
        volumes:
            - '/volume2/DOCKER-DATA/Ghostfolio/redis:/bitnami/redis/data'
        restart: unless-stopped
        image: bitnami/redis:latest
```
