### ISSUE TITLE
Acessing Ghostfolio behind a reverse-proxy in Docker

### ISSUE THREAD

**Issue by GitBOUF** [ghostfolio/ghostfolio#1004]
Hello,

I've currently setup Ghostfolio in Docker behind a Traefik 2 container. All other apps in my docker-compose works behind Traefik, except Ghostfolio. I've noticed that the docker image pulled from DockerHub for Ghostfolio is currently setup to listen by default on localhost. Is there a way to change it to listen on 0.0.0.0 instead?

Since we can change the port with the PORT environment variable, I've tried to setup the HOST environment variable, but no success.
PORT=3333
HOST=0.0.0.0

And the logs keep showing on every restart:
`Listening at http://localhost:3333`

Just like we can set the PORT environment variable, having a HOST environment variable would be useful for changing the interface to listen on.

Here's how Ghostfolio is setup in my docker-compose:
``` YAML
  ghostfolio:
    image: ghostfolio/ghostfolio:latest
    container_name: ghostfolio
    networks:
      - traefik_proxy
      # Use an internal network for the database and redis
      - ghostfolio_network
     #No need to open the port here, Traefik handles it.
     #ports:
     # - 3333:3333
    depends_on:
      - ghostfolio-db
      - ghostfolio-redis
    environment:
      PORT: 3333
      HOST: 0.0.0.0
      REDIS_HOST: ghostfolio-redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${GHOSTFOLIO_REDIS_PASSWORD}
      POSTGRES_DB: ghostfolio
      POSTGRES_USER: ghostfolio
      POSTGRES_PASSWORD: ${GHOSTFOLIO_DB_PASSWORD}
      POSTGRES_PORT: 5432
      DATABASE_URL: postgresql://ghostfolio:${GHOSTFOLIO_DB_PASSWORD}@ghostfolio-db:5432/ghostfolio?sslmode=prefer
      ACCESS_TOKEN_SALT: ${GHOSTFOLIO_ACCESS_TOKEN_SALT}
      JWT_SECRET_KEY: ${GHOSTFOLIO_JWT_SECRET_KEY}
    labels:
      - "traefik.enable=true"
      ## HTTP Routers Auth
      - "traefik.http.routers.ghostfolio-rtr.entrypoints=websecure"
      - "traefik.http.routers.ghostfolio-rtr.rule=Host(`ghostfolio.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.ghostfolio-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.ghostfolio-rtr.ghostfolio=ghostfolio-svc"
      - "traefik.http.services.ghostfolio-svc.loadbalancer.server.port=3333"
```

Am I missing something that would make my ghostfolio instance accessible behind a domain just like the live demo at [ghostfol.io](https://ghostfol.io)? 

My instance will be setup behind an authelia auth for personal use only on my local network; so no commercial nor public use (I just want to make that clear).

Thank you ! The app is really nice, and hopefully we can find a solution to this issue.
