### ISSUE TITLE
Infinite loading

### ISSUE THREAD

**Issue by enzofoucaud** [ghostfolio/ghostfolio#1184]
Hey,

I have a problem with self-hosting.
I have a infinite loading screen.

docker-compose.yml :
```
version: '3.7'

networks:
  web:
    name: web
    external: true
  internal:
    name: internal
    external: false

services:
  ghostfolio:
    image: ghostfolio/ghostfolio:latest
    container_name: ghostfolio
    env_file:
      - ../.env
    environment:
        ACCESS_TOKEN_SALT: ${ACCESS_TOKEN_SALT}
        BASE_CURRENCY: ${BASE_CURRENCY}
        DATABASE_URL: ${DATABASE_URL}
        JWT_SECRET_KEY: ${JWT_SECRET_KEY}
        PORT: ${PORT}
        REDIS_HOST: 'redis'
        REDIS_PASSWORD: ${REDIS_PASSWORD}
        REDIS_PORT: ${REDIS_PORT}
    ports:
      - 3333:3333
    networks:
      - web
      - internal
    labels:
      # Traefik v2
      - .....

  redis:
    image: 'redis:alpine'
    container_name: ghostfolio_redis
    networks:
      - internal
 ```

![image](https://user-images.githubusercontent.com/15039645/186131461-ffee3024-8437-4df9-a1c1-f972fae571c2.png)
