### ISSUE TITLE
Reference to index.html set to incorrect path

### ISSUE THREAD

**Issue by tech1ndex** [ghostfolio/ghostfolio#1370]
**Bug Description**

During a new deployment of the Ghostfolio v1.203.0 container, the reference to index.html points to '/ghostfolio/apps/client/index.html' however upon further inspection, the path to index.html should actually refer to '/ghostfolio/apps/client/<lang>'

This results in the following error when navigating to the main URL:

```
{"statusCode":404,"message":"ENOENT: no such file or directory, stat '/ghostfolio/apps/client/index.html'"}
```

**To Reproduce**

1. Deploy v.1.203.0 version of ghostfolio container
2. Confirm clean start-up and connection to database in logging
3. Navigate to http://hostname:3333

**Expected behavior**

The ghostfolio homepage loads.

**Screenshots**

<img width="856" alt="image" src="https://user-images.githubusercontent.com/50547519/196052920-8402bada-2a2a-48c3-b9f3-24c86ff38088.png">

**Environment**

- Ghostfolio Version 1.203.0
- Chrome Version 106.0.5249.119
- Mac OS 12.6

**Addtional Information**

<img width="1134" alt="image" src="https://user-images.githubusercontent.com/50547519/196053109-7f2194f0-2c4b-4bd4-895a-99696618ae16.png">

**Comment by dtslvr** [comment]
Hi @tech1ndex

Is your issue related with https://github.com/ghostfolio/ghostfolio/issues/1259#issuecomment-1248252870?

**Comment by dtslvr** [comment]
Okay great! Thanks for the feedback.

Yes, I think it's a good idea to document it, because the question has been raised multiple times. Not so sure if it fits to _Supported Environment Variables_, because I think you cannot set it via environment variable.

Maybe add an information below the table?

> Please ensure that `NODE_ENV: production` has been set in your _Node.js_ environment.

**Comment by tech1ndex** [comment]
Hi @dtslvr ,

Hmm, actually that is where I set it in order to get it working, here is my working container spec section below:

```
    spec:
      containers:
        - env:
            - name: PORT
              value: "3333"
            - name: BASE_CURRENCY
              value: "CAD"
            - name: ACCESS_TOKEN_SALT
              value: "redacted"
            - name: JWT_SECRET_KEY
              value: "redacted"
            - name: DATABASE_URL
              value: "redacted"
            - name: REDIS_HOST
              value: "redacted"
            - name: REDIS_PASSWORD
              value: "redacted"
            - name: REDIS_PORT
              value: "6379"
            - name: NODE_ENV
              value: production
```

Haven't tested with a docker-compose but I assume it would be the same since Kubernetes is just passing those values into docker anyways.

**Comment by IrwenXYZ** [comment]
hi I would like to bump this. I'm using docker-compose but still seem to run into this issue even though I've set `NODE_ENV` to production in both docker-compose and the .env file. here's my docker compose.
```
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@ghostfolio_postgres:5432/${POSTGRES_DB}?sslmode=prefer
      - NODE_ENV=production
      - REDIS_HOST=ghostfolio_redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - ghostfolio-bridge
    env_file:
      - .env
```
