### ISSUE TITLE
Cannot benchmark portfolio to Indexes successfully [BUG]

### ISSUE THREAD

**Issue by MetaBliss** [ghostfolio/ghostfolio#1850]
**Bug Description**

I cannot compare my portfolio to benchmark indexes like S&P 500 or TSX. I saw in the Ghostfolio demo version that this comparison to benchmarks can be done. I was told via Slack that first I need to add the Index ETF in the GUI for it to produce a Symbol Profile ID in the database and then I can delete the entry. And that for the comparison button to compare to benchmarks cannot be done via GUI and must be done by editing the database. Even after I edit the database to add benchmark symbol IDs in, I still cannot compare my portfolio to the chosen benchmark indexes. In fact, my Ghostfolio instance has other errors as well after making the database table change which I also need to address. I attempted to also test on a fresh instance of Ghostfolio installed as a test instance and I cannot get the benchmark portfolio part to work at all. Please see more details below. 

**To Reproduce**

1)  I created a new instance of Ghostfolio successfully and using the GUI i added several ETFs that I wanted to track as benchmarks. This included SPY, VOO, and XIU which all track various indexes like S&P 500 and TSX. For comparison I also added a single stock ([BCE.TO](http://bce.to/)) so I could try to see if the comparison to benchmarks works.

2) To edit the database I installed pgAdmin, connected to the database successfully and went to the "symbolProfile" table where I saw the symbolProfile ID for several Index ETFs I added along with a stock (BCE.TO). See snapshot of this. 
<img width="2304" alt="Screen Shot 2023-04-10 at 6 01 26 PM" src="https://user-images.githubusercontent.com/84720384/231016758-f2932bc9-9532-4d4c-8d91-5fbcb23e4876.png"> I copied the value for the SPY ETF which has a red box around it in the snapshot. 

3) Then I went to the "Property" table and added a key for "BENCHMARKS" and pasted the value from the "symbolProfileID" for the SPY index ETF to this table.  I have provided a snapshot here to. 
<img width="1091" alt="Screen Shot 2023-04-10 at 6 06 04 PM" src="https://user-images.githubusercontent.com/84720384/231016864-c0682a56-9aaf-42f6-8b26-9a0aec9ffbca.png"> Then I saved the entry and returned back to my Ghostfolio instance.

4) I refreshed my Ghostfolio instance and I did see a dropdown bar in the portfolio section of Ghostfolio's GUI but no comparisons were drawn between my stocks and the benchmark SPY Index ETF. It just showed a flat line like in this snapshot. it wasnt showing me a historical graph of the SPY's performance over time. Attached is a screenshot of it and it didnt compare to my BCE stock which I added in to test against the benchmark.  

I tested this on a completely new Ghostfolio instance (on the latest 1.252.1.

In addition, I also got errors in my logs. 

```
https://query2.finance.yahoo.com/v7/finance/download/TD.TO?interval=1d&events=history&includeAdjustedClose=true&period1=1680912000&period2=1681084800
[Nest] 234  - 04/10/2023, 6:45:27 PM   ERROR [DataProviderService] Error: Could not get historical market data for TD.TO (YAHOO) from 2023-04-08 to 2023-04-10: [HTTPError] Not Found
[Nest] 235  - 04/10/2023, 6:53:30 PM   ERROR [ExchangeRateDataService] No exchange rate has been found for CADUSD
[Nest] 235  - 04/10/2023, 6:53:31 PM     LOG [DataGatheringService] Asset profile data gathering has been completed for BCE.TO (YAHOO).
[Nest] 235  - 04/10/2023, 6:53:32 PM   ERROR [ExchangeRateDataService] No exchange rate has been found for CADUSD
[Nest] 235  - 04/10/2023, 6:53:32 PM   ERROR [ExchangeRateDataService] No exchange rate has been found for CADUSD
[Nest] 235  - 04/10/2023, 6:53:32 PM    WARN [PortfolioCalculator] Missing initial value for symbol BCE.TO at 2023-03-14
[Nest] 235  - 04/10/2023, 6:53:32 PM   ERROR [ExchangeRateDataService] No exchange rate has been found for CADUSD
[Nest] 235  - 04/10/2023, 7:04:03 PM     LOG [DataGatheringService] Job GATHER_HISTORICAL_MARKET_DATA with data {"dataSource":"YAHOO","date":"2023-03-14T04:00:00.000Z","symbol":"BCE.TO"} already exists.
[Nest] 235  - 04/10/2023, 7:04:04 PM     LOG [DataGatheringService] Job GATHER_ASSET_PROFILE with data 
[Nest] 235  - 04/10/2023, 7:04:28 PM     LOG [DataGatheringProcessor (GATHER_HISTORICAL_MARKET_DATA)] Historical market data gathering has been completed for SPY (YAHOO).
```

**Expected behavior**

I would have expected to be able to compare the performance of my portfolio to indexes such as S&P 500, TSX, etc. 

**Environment**

For environment I updated to 1.252.1 and I am running a Synology NAS with Docker installed.

**Comment by MetaBliss** [comment]
To help any others that may come across this issue, I figured out that the source of my problems in the post above were because I had an incorrect environmental variable set in my Docker Compose for Ghostfolio. I had read someone else's Ghostfolio docker compose and it incorrectly had set the TZ (timezone variable) set. As far as I know, there is no TZ environmental variable that should be set in Ghostfolio. Once I removed the TZ environmental variable from my Docker Compose, everything functioned properly. Below is my working Docker Compose for anyone interested in getting set up. Change anything in the ${} to your values. 

To get the benchmarks working do the following steps:

1) Set up Ghostfolio and in the GUI, add the Index ETF funds that you want to compare as benchmarks to your portfolio. I chose SPY, VOO, VTI, and XIU which all track various indexes like S&P 500 and TSX. By doing this first, the database will generate "symbolProfileID" numbers for each ETF fund which you will need later. 

2) Install a database management program. There's several out there like Adminer, Prisma, pgAdmin. I opted to pick pgAdmin and installed it and then connected my database to it. Then I went to the "symbolProfile" table in the database where I saw the symbolProfile ID for several Index ETFs. See snapshot of this for an example with SPY.
    Screen Shot 2023-04-10 at 6 01 26 PM I copied the value for the SPY ETF which has a red box around it in the snapshot.

    Then I went to the "Property" table and added a key for "BENCHMARKS" and pasted the value from the "symbolProfileID" for the SPY index ETF to this table. 
    Screen Shot 2023-04-10 at 6 06 04 PM Then I saved the entry and returned back to my Ghostfolio instance.

3) Refresh your Ghostfolio instance and if you did everything correctly you will see a dropdown bar in the portfolio section of Ghostfolio's GUI  allowing you to compare your stock portfolio to the benchmark SPY Index ETF. 

And that's it. Make sure to thank the developer(s) for this product, they are doing phenomenal work and deserve more support. 

Below is my docker compose. I am closing this ticket as I figured out what the problem was for me. If you're reading this, hope you get up and running with the benchmarks to.

```
version: "3.9"
services:
  ghostfolio_redis:
    image: redis
    container_name: ghostfolio_redis
    hostname: ghostfolio_redis
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
    user: ${YOUR_UID:YOUR_GID}
    environment:
      - TZ=${YOUR_TIMEZONE}
    volumes:
      - /volume1/docker/ghostfolio/redis:/data  #this is a persistent volume mount which should be changed to your config
    restart: always
    networks:
      - ghostfolio-internal

  ghostfolio_postgres:
    image: postgres
    container_name: ghostfolio_postgres
    hostname: ghostfolio_postgres
    security_opt:
      - no-new-privileges:true
    user: ${YOUR_UID:YOUR_GID}
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USER}"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - /volume1/docker/ghostfolio/db:/var/lib/postgresql/data  #this is a persistent volume mount which should be changed to your config
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PW}
    restart: always
    networks:
      - ghostfolio-internal
      
  ghostfolio:
    image: ghostfolio/ghostfolio:latest
    container_name: ghostfolio
    security_opt:
      - no-new-privileges:true
    user: ${YOUR_UID:YOUR_GID}
    environment:
      - NODE_ENV=production
      - ACCESS_TOKEN_SALT=${ACCESS_TOKEN}
      - BASE_CURRENCY=CAD
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - REDIS_HOST=ghostfolio_redis
      - REDIS_PASSWORD=
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PW}@ghostfolio_postgres:5432/${DB_NAME}?sslmode=prefer
    ports:
      - 3333:3333
    restart: always
    networks:
      - ghostfolio-internal
      - reverseproxy
    depends_on:
      ghostfolio_postgres:
        condition: service_started
      ghostfolio_redis:
        condition: service_started

networks:
  ghostfolio-internal:
  reverseproxy:
    external: true
```
