### ISSUE TITLE
[BUG] Can't reach database server

### ISSUE THREAD

**Issue by ilijaleko** [ghostfolio/ghostfolio#1931]
**Please make sure your database server is running at `postgres`:`5432`.**

Should the docker-compose file contain the "depends_on" feature because currently the backend starts before the database which needs to be ready at that time?

When running "docker-compose --env-file ./.env -f docker/docker-compose.yml up -d" the backend fails with the message: "Please make sure your database server is running at `postgres`:`5432`."

**Potential solution is to implement depends_on in docker-compose.yml file**

```
ghostfolio:
  #...
  depends_on:
        postgres:
          condition: service_healthy

postgres:
  #...
  healthcheck:
        test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
        interval: 10s
        timeout: 5s
        retries: 5
```
