### ISSUE TITLE
[BUG] Docker Secrets not accepted

### ISSUE THREAD

**Issue by prononext** [ghostfolio/ghostfolio#2115]
With the compose file https://github.com/ghostfolio/ghostfolio/blob/main/docker/docker-compose.yml

I tried to use the ENVs in following style:

`POSTGRES_DB_FILE: "/run/secrets/POSTGRES_DB"
`

and store the sensible informations in Docker secrets. 

Sadly none of the parameters support the _FILE addition to get the secrets working with the docker stack.

We would need the following parameters accept the _FILE suffix to support secrets:

- DATABASE_URL
- POSTGRES_DB
- POSTGRES_PASSWORD
- POSTGRES_USER
- REDIS_PASSWORD
- ACCESS_TOKEN_SALT
- JWT_SECRET_KEY

I hope that is in the interest of everyone using that software in a safe and secure way. 
By the way redis and postgres support it out of the box without any issues. 

docker secrets are used the following way after you create them in your docker environment  https://docs.docker.com/engine/swarm/secrets/
```
version: '3.8'

secrets:
  DATABASE_URL:
    name: DATABASE_URL
    external: true   
## one entry like this for every secret

services:

  ghostfolio:
    image: ghostfolio/ghostfolio:1.285.0
    secrets: # reference the secrets you use individually for every service
      - DATABASE_URL
    environment:
      DATABASE_URL_FILE:  "/run/secrets/DATABASE_URL"
## and so on for every secret you use
```
