### ISSUE TITLE
[BUG] Error: P1001: Can't reach database server is running at `ghostfolio-postgres-1` : `5432`

### ISSUE THREAD

**Issue by eudaldgr** [ghostfolio/ghostfolio#2121]
**Bug Description**
Self-hosted ghostfolio on Synology using a docker-compose. It's been stable since first installed more than 6 months ago. I ran into a problem after upgrading DSM to 7.2. After upgrade, the ghostfolio docker container fails to start with this error:

```
Error: P1001: Can't reach database server is running at `ghostfolio-postgres-1` : `5432`
```

I tried also with the docker-compose file from this github and the .env.example variables, same error.

**To Reproduce**

1. Create docker-compose.yml
``` yaml
version: "3.7"

services:
  server:
    image: ghostfolio/ghostfolio:1.269.0@sha256:096ea10a7e9c8c471701da78d3aeb8434879e465b36b3564d6bb424bc47c2b3d
    ports:
      - 3333:3333
    restart: on-failure
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 3333
      ACCESS_TOKEN_SALT: SOME_SUPER_SECRET_SALT
      DATABASE_URL: postgresql://MY_DB_USER:MY_DB_PWD@ghostfolio-postgres-1:5432/MY_DB_NAME?sslmode=disable
      JWT_SECRET_KEY: SOME_SUPER_SECRET_KEY
      POSTGRES_DB: MY_DB_NAME
      POSTGRES_USER: MY_DB_USER
      POSTGRES_PASSWORD: MY_DB_PWD
      REDIS_HOST: ghostfolio-redis-1
      REDIS_PASSWORD: MY_REDIS_PWD
      REDIS_PORT: 6379
      BASE_CURRENCY: EUR
  
  postgres:
    image: postgres:14-bullseye@sha256:c2a30d08a6f9e6c365595fd086c9e0436064c52425f15f72379ecf0807bac518
    restart: on-failure
    stop_grace_period: 1m
    environment:
      POSTGRES_USER: MY_DB_USER
      POSTGRES_PASSWORD: MY_DB_PWD
      POSTGRES_DB: MY_DB_NAME
      PGDATA: /var/lib/postgresql/data
    volumes:
      - /volume1/docker/ghostfolio/data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:6.2-bullseye@sha256:5cdb2ac6f780e1d250787f4a887c1ed1166e3389757189ea913059409acc6f7c
    restart: on-failure
    command: >
      --requirepass MY_REDIS_PWD
    volumes:
      - /volume1/docker/ghostfolio/data/redis:/data
```
2. Build docker containers with `sudo docker-compose -f docker-compose.yml up -d`
3. Wait untill ghostfolio container stops.

**Logs**
With default docker-compose file from this repo:

<html>
<body>

date | stream | content
-- | -- | --
2023/07/04 11:39:20 | stdout | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2023/07/04 11:39:20 | stderr | error Command failed with exit code 1.
2023/07/04 11:39:20 | stdout | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2023/07/04 11:39:20 | stderr | error Command failed with exit code 1.
2023/07/04 11:39:20 | stderr | Please make sure your database server is running at `postgres`:`5432`.
2023/07/04 11:39:20 | stderr |  
2023/07/04 11:39:20 | stderr | Error: P1001: Can't reach database server at `postgres`:`5432`
2023/07/04 11:39:20 | stdout |  
2023/07/04 11:37:13 | stdout | Datasource "db": PostgreSQL database "ghostfolio-db", schema "public" at "postgres:5432"
2023/07/04 11:37:13 | stdout | Prisma schema loaded from prisma/schema.prisma
2023/07/04 11:37:12 | stdout | $ prisma migrate deploy
2023/07/04 11:37:11 | stdout | $ yarn database:migrate && yarn database:seed && node main
2023/07/04 11:37:11 | stdout | yarn run v1.22.19

</body>
</html>

**Environment**

- Self-hosted
- Ghostfolio Version 1.286.0 & 1.269.0
- Google Chrome 114.0.5735.199
- Synology DSM 7.2-64570 Update 1

**Additional context**

- Docker Compose version v2.9.0-6413-g38f6acd
- Docker version 20.10.23, build 876964a
