### ISSUE TITLE
[FEAT] Docker: Healthcheck for the ghostfolio app

### ISSUE THREAD

**Issue by longstone** [ghostfolio/ghostfolio#2304]
Docker Compose is missing a Healthcheck for ghostfolio app.

I propose to add a healthcheck.

My proposal:

docker-compose.yml
```
services:
  ghostfolio:
 ....
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3333"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
....
```

but this will require curl to be installed (Dockerfile).

Is there any reason to not do so?
If this sounds good to you, I could create a PR.
