### ISSUE TITLE
[BUG] Yahoo Missing historical market data / Data Provider Error

### ISSUE THREAD

**Issue by sameleff** [ghostfolio/ghostfolio#2640]
**Bug Description**

When I attempt to add a new stock asset via the `YAHOO` Data_Source, the ghostfolio logs output `WARN [PortfolioCalculator] Missing historical market data for APL (YAHOO)` and I receive a "Data provider error" when I navigate to any of the pages underneath Overview or Portfolio (except Market Data and Activities).

**To Reproduce**

1. Add activity data (via csv/json importer or manually via the GUI)
2. Check Admin Control > Market Data and confirm that price data exists for the date of the activity that was just entered (it does)
3. Navigate to the Overview main page; graph is a horizontal line and an exclamation point appears above the portfolio value. Clicking the exclamation point displays a popup that contains the data provider error.

**Expected behavior**

1. Add activity data
2. Ghostfolio automatically imports asset profile data & historical market data (from the oldest date until the current day)
3. Overview & portfolio charts update using database price data to display performance correctly

**Screenshots**

Starting Ghostfolio; YAHOO crumb obtained successfully:
![image](https://github.com/ghostfolio/ghostfolio/assets/105563130/ffe073e5-9931-44b2-9949-c576413d496b)

Adding activity:
![image](https://github.com/ghostfolio/ghostfolio/assets/105563130/b288bf13-725c-4802-9db8-b17d1ebe1372)

Confirming data exists in the admin panel:
Note that the date for my submitted activity (11/11/2013) is highlighted green in the screenshot, indicating price data is present.
![image](https://github.com/ghostfolio/ghostfolio/assets/105563130/60b9e548-cda4-4010-984a-da20a03a92b1)
Verification that data was pulled successfully:
![image](https://github.com/ghostfolio/ghostfolio/assets/105563130/071de36c-8922-40b7-bee6-4cb1974017b7)

Error on Overview page:
![image](https://github.com/ghostfolio/ghostfolio/assets/105563130/1be8ce20-0b0e-470b-9645-1989a5297479)
![image](https://github.com/ghostfolio/ghostfolio/assets/105563130/4e152ba7-a2db-4324-bb21-be5cf56326e9)

**Logs**

See above.

**Environment**

- Self-hosted
- Ghostfolio Version 2.19.0
- Web browser: Brave
- OS: Hosted on UNRAID 6.12.4 using docker; web browser accessed on Win10 Pro 64bit machine

**Additional context**

There seem to be several other bug reports about similar issues. I submitted this one in order to provide additional context. This behavior occurs for many different tickers, not just AAPL. Additionally, I've noticed that for some tickers (e.g. VTSAX) the `YAHOO` Data_Source is unable to pull a full history of data. For example, if I submit activity for 11/1/2013, the farthest date returned in the admin panel occurs sometime in 2014. I confirmed with the YAHOO API that data does indeed exist prior to 1/1/2014, so I'm not sure why this is happening. This may be a separate bug...

**Comment by hapigandhi** [comment]
I'm having the same issue

**Comment by nodiaque** [comment]
Same issue here. I can see the historical data in the stocks and market but when I check into activity or my portfolio, it fail with same error.

**Comment by joshvermette** [comment]
Just want to note here that I am having the same issues. Running on unraid via docker as well

**Comment by dtslvr** [comment]
Ghostfolio for _Unraid_ is a community project. Ideally, you ask for help there as we are not familiar with it.

Could it be related to https://github.com/ghostfolio/ghostfolio/issues/2669?

**Comment by joshvermette** [comment]
So I tried multiple times swapping the TZ container variable to many different options (including null) to no success.  I ended up changing my unraid timezone to UTC and reloading the container with TZ = ''  and now I have balances showing! I was then able to set the timezone in my unraid settings back to my timezone and it is still working.

**Comment by dtslvr** [comment]
> I was having the same issue and it appears to be an issue with the unraid community version of the app.

Thank you for the summary, @RyanShahidi. Is it possible to fix it there once and for all?

**Comment by nodiaque** [comment]
The CA should use the default docker. Do we have a different Docker on unraid than the official one? That would be stupid

**Comment by cjboyle** [comment]
I had the same issue with the TrueCharts version, and I got it working again by setting the chart's timezone to "Factory" in the dropdown menu (setting the environment variable directly with ```TZ=""``` isn't allowed as it's part of the fixedEnv).

**Comment by JPDVM2014** [comment]
> The CA should use the default docker. Do we have a different Docker on unraid than the official one? That would be stupid

It looks like it does reference the official image.

**Comment by nodiaque** [comment]
For me, ghostfolio does nothing. I have no history, no chart, nothing even when I entered manually (cause it doesn't import from wealthsimple).

**Comment by joshvermette** [comment]
@nodiaque are you running on unraid? Go into your settings, change your timezone to UTC and then restart all your ghostfolio related containers. Make sure no TZ variable is set in the container either. That worked for me

**Comment by nodiaque** [comment]
Yes On unraid. Change timezone in ghostfolio or timezone of unraid?

**Comment by joshvermette** [comment]
In unraid

**Comment by nodiaque** [comment]
This will affect other container that I'm running so I cannot do that, specially my home automation one.

**Comment by nodiaque** [comment]
Also tz var is automatically added by unraid to all docker container if you check the run cmd

**Comment by sameleff** [comment]
I cannot express how excited I am that this fix works! I really wanted Ghostfolio to work but gave up a long time ago. Thanks to everyone who continued to comment on this thread, especially @RyanShahidi for identifying the solution. I can confirm that setting the TZ environment variable to a blank value works (previously I had it set to my current timezone, which is something that I typically do out of habit for every new docker container that I create). For anyone following later, here is the working docker-compose file:

```
version: '3.9'
services:
  ghostfolio:
    image: ghostfolio/ghostfolio:latest
    env_file:
      - ../.env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?connect_timeout=300&sslmode=prefer
      NODE_ENV: production
      REDIS_HOST: redis
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      TZ: 
    ports:
      - 3333:3333
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:3333/api/v1/health']
      interval: 10s
      timeout: 5s
      retries: 5
  postgres:
    image: postgres:15
    env_file:
      - ../.env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    env_file:
      - ../.env
    command: ['redis-server', '--requirepass', $REDIS_PASSWORD]
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli --pass $REDIS_PASSWORD ping | grep PONG']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres:
```
