### ISSUE TITLE
[Bug] Redis Connection Error

### ISSUE THREAD

**Issue by theflyer08** [ghostfolio/ghostfolio#3745]
After the latest docker-update (made by watchdog) the landing page can't be reached. 
In Portainer no network and port is bind to the Ghostfolio container.

**To Reproduce**

1. Every time when the landing page is accessed

**Expected behavior**

Landing page opens

**Logs**

Redis Connection Error:  [ErrorReply: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?]
[Nest] 107  - 09/09/2024, 7:27:41 AM   ERROR [ExceptionHandler] ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?

**Environment**

Docker
Self hosted
Debian 12

**Comment by dtslvr** [comment]
The redis configuration has recently changed due to an update of the cache library:
https://github.com/ghostfolio/ghostfolio/blob/bdb3a8f1dc5f89ebda2f081320a2033c774a0ded/apps/api/src/app/redis-cache/redis-cache.module.ts#L25

Maybe the logic here is not correct if you don't have a password? The easiest way would probably be to define `REDIS_PASSWORD` in your `.env` file (see [.env.example](https://github.com/ghostfolio/ghostfolio/blob/bdb3a8f1dc5f89ebda2f081320a2033c774a0ded/.env.example)) and restart the containers.

**Comment by theflyer08** [comment]
Hi @dtslvr,
I entered a redis-password in the .env-file and rebooted the machine. It didn't work. This is the corresponding log:

> Redis Connection Error:  [ErrorReply: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?]
> [Nest] 108  - 09/09/2024, 1:41:08 PM   ERROR [ExceptionHandler] ERR AUTH <passwortd> called without any password configured for the default user. Are you sure your configuration is correct?
> 

I also tried to enter the same redis-password in the docker-compose.yml file. But this doesn't help either.

**Comment by sujan46** [comment]
@theflyer08  Had the same issue v2.105.0. fixed it by updating my docker-compose file. May be relevant?

https://github.com/ghostfolio/ghostfolio/commit/9bf68b0d208c7a1292a96190b43bcf3c59ce0d26

https://github.com/ghostfolio/ghostfolio/blob/557a0bf8080870943f70dfda37f6ae5cb0666a4e/docker/docker-compose.yml#L57

**Comment by theflyer08** [comment]
@sujan46: I used an updated docker-compose.yml file. But the error message stays the same.

**Comment by theflyer08** [comment]
I tried out the latest .env and the latest docker-compose.yml file. I tried it with and without Redis password. The redis connection error stays the same.

**Comment by flowcool** [comment]
Here's what I've done for that:

```
  ghost_redis:
    image: redis:alpine
    container_name: ghost_redis
    user: ${PUID}:${PGID}
    restart: unless-stopped
    healthcheck:
      #test: ['CMD-SHELL', 'redis-cli --pass $REDIS_PASSWORD ping | grep PONG']
      test: [ "CMD", "redis-cli", "--pass", $REDIS_PASSWORD, "--no-auth-warning", "ping | grep PONG" ]
      interval: 10s
      timeout: 5s
      retries: 5
    command: ['redis-server', '--requirepass', $REDIS_PASSWORD]
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      PUID: ${PUID}
      PGID: ${PGID}
```
