### ISSUE TITLE
[BUG] Ghostfolio docker (armv7) doesn't starts due to prisma

### ISSUE THREAD

**Issue by rinyakok** [ghostfolio/ghostfolio#4832]
**Bug Description**

Hello,

I wanted to deploy ghostfolio armv7 version self-hosted on my raspberry pi 4/B. Unfortunately the docker runs into error due to prisma during startup in database migration.

Here is the docker log:

> + npx prisma migrate deploy
> Running database migrations
> 
> prisma:warn Prisma only officially supports Linux on amd64 (x86_64) and arm64 (aarch64) system architectures (detected "arm" instead). If you are using your own custom Prisma engines, you can ignore this warning, as long as you've compiled the engines for your system architecture "armv7l".
> 
> Error: Failed to fetch the engine file at https://binaries.prisma.sh/all_commits/2060c79ba17c6bb9f5823312b6f6b7f4a845738e/linux-arm-openssl-3.0.x/libquery_engine.so.node.gz - 404 Not Found

It keeps trying the migration continuously and ghostfolio doesn't start 

**To Reproduce**

1. Docker containers (redis,postgres,ghostfolio) are created from docker-compose.yml (see attached)

[docker-compose.yml.txt](https://github.com/user-attachments/files/20606423/docker-compose.yml.txt)

```yaml
name: ghostfolio
services:
  ghostfolio:
    image: ghostfolio/ghostfolio@sha256:90b6a69ef5a42fb21d91e64fb75be1e58ce41ec1af10d084d67a3952d00d4f36
    container_name: ghostfolio
    restart: unless-stopped
    init: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@ghostfolio-postgres:5432/${POSTGRES_DB}?connect_timeout=300&sslmode=prefer
      - NODE_ENV=production
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - ACCESS_TOKEN_SALT=${ACCESS_TOKEN_SALT}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING=${PRISMA_ENGINES_CHECKSUM_IGNORE_MISSING}
    ports:
      - 3333:3333
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:3333/api/v1/health']
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: arm32v7/postgres:15-alpine
    container_name: gf-postgres
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_READ_SEARCH
      - FOWNER
      - SETGID
      - SETUID
    security_opt:
      - no-new-privileges:true
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test:
        ['CMD-SHELL', 'pg_isready -d "$${POSTGRES_DB}" -U $${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: arm32v7/redis:alpine
    container_name: gf-redis
    restart: unless-stopped
    user: '999:1000'
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/Budapest
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    healthcheck:
      test:
        ['CMD-SHELL', 'redis-cli --pass "$${REDIS_PASSWORD}" ping | grep PONG']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres:



```

2. After the containers are created and started I can see the redis & postgres running and healthy, but ghostfolio is just starting

I'm not able to connect to ghostfolio via port 3333

**Expected Behavior**

**Screenshots**

![Image](https://github.com/user-attachments/assets/7f1b50df-e3db-4be7-af8f-bb4725539920)

**Logs**

[_ghostfolio_logs.txt](https://github.com/user-attachments/files/20606674/_ghostfolio_logs.txt)

**Environment**

- Ghostfolio Version X.Y.Z
- Self-hosted
- disabled
- Firefox/Chrome
- Linux Debian

**Additional Context**
