### ISSUE TITLE
tables don't exist on new docker deployment

### ISSUE THREAD

**Issue by darkknight7777777** [ghostfolio/ghostfolio#929]
I'm getting the below errors on a fresh docker setup (fresh ubuntu, etc)
```

today at 5:31:01 PM(node:1) UnhandledPromiseRejectionWarning: Error: 
today at 5:31:01 PMInvalid `this.prismaService.authDevice.findUnique()` invocation in
today at 5:31:01 PM/ghostfolio/apps/api/main.js:1:38418
today at 5:31:01 PM
today at 5:31:01 PM→ 1 (()=>
today at 5:31:01 PM  The table `public.Property` does not exist in the current database.
today at 5:31:01 PM    at Object.request (/ghostfolio/apps/api/node_modules/@prisma/client/runtime/index.js:45578:15)
today at 5:31:01 PM    at async PrismaService._request (/ghostfolio/apps/api/node_modules/@prisma/client/runtime/index.js:46405:18)
today at 5:31:01 PM(Use `node --trace-warnings ...` to show where the warning was created)
today at 5:31:01 PM(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
today at 5:31:01 PM(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
today at 5:31:01 PM(node:1) UnhandledPromiseRejectionWarning: Error: 
today at 5:31:01 PMInvalid `this.prismaService.authDevice.findUnique()` invocation in
today at 5:31:01 PM/ghostfolio/apps/api/main.js:1:28152
```

this is my docker-compose, slightly tweaked from the one provided. I've tried postgres12 & 13 what did I do wrong?

```
version: '3.9'
services:
  ghostfolio:
    image: ghostfolio/ghostfolio:latest
    container_name: ghostfolio
    restart: "unless-stopped"
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://ghostfolio:password@postgres:5432/ghostfolio-db?sslmode=prefer
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ACCESS_TOKEN_SALT: string
      # run "openssl rand -base64 32" for each random string
      ALPHA_VANTAGE_API_KEY: string
      JWT_SECRET_KEY: string
      PORT: 3333
    ports:
      - 3333:3333

  postgres:
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_DB: ghostfolio-db
      POSTGRES_USER: ghostfolio
      POSTGRES_PASSWORD: string
    volumes:
      - /etc/config/postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    restart: "unless-stopped"
```
